const raids: { [key: string]: string[] } = {
  "Last Wish": [
    "Free: foww genewations",
    "Kalli: failsafe wish",
    "Kalli: chaos doors",
    "Kalli: wrong plate cleansed",
    "Kalli: someone dies to orb explosion",
    "Shuro Chi: someone dies to bridge jumping",
    "Shuro Chi: someone dies to plate damage",
    "Shuro Chi: teacup spins and drops someone",
    "Shuro Chi: eye of riven is picked up",
    "Morgeth: someone dies to ascendant plane jumping",
    "Morgeth: platforms in ascendant plane despawn before everyone gets across",
    "Morgeth: fail to cleanse stuck person",
    "Morgeth: someone dies to axion darts",
    "Vault: captain successfully booped into center room",
    "Vault: non-standard symbol name used",
    "Vault: wrong plate cleansed",
    "Vault: knight sticks sword in plate",
    "Riven: cheese is done",
    "Riven: directions for cleanse without number chart",
    "Riven: missed stun",
    "Riven: wrong eye is shot when eyes are known",
    "QW: someone gets lost",
    "QW: multiple people get pulled inside the heart at once",
    "QW: heart timer extended too early (> 10 seconds on timer)",
    "QW: someone dies to creeping darkness while going down elevator",
  ],
  Leviathan: [
    "Free: getting lost in underbelly",
    "Castellum: colossi aggro'd",
    "Castellum: flag order is guessed correctly",
    "Castellum: flag reclaimed",
    "Castellum: group does castellum 4x instead of underbelly",
    "Dogs: alerting dogs with 0 stacks",
    "Dogs: crystal holder alerting dogs",
    "Dogs: 2-phase",
    "Dogs: someone dies to beast handler",
    "Baths: someone runs out of buff",
    "Baths: a chain completely resets",
    "Baths: 2-phase",
    "Baths: accidental suicide during dps",
    "Gauntlet: runner dies due to missed arrows",
    "Gauntlet: someone dies to adds",
    "Gauntlet: a psion is left alive",
    "Gauntlet: wipe due to too few orbs after final round",
    "Calus: someone dies by falling in a hole in shadow realm",
    "Calus: wrong psion punched",
    "Calus: fail to break shield in time",
    "Calus: less than x50 for dps",
    "Underbelly: death by watcher explosion",
    "Underbelly: death by falling off pipes",
    "Underbelly: fail to kill all watchers when trying to open a chest",
    "Underbelly: death by fan",
  ],
  "Garden of Salvation": [
    "Big portal bamboozle",
    "Too loud eye callouts",
    "Dying with motes",
    "No champ mods",
    "Wrong person picking up motes",
    "Tether orgy",
    "Cyclops in the DPS phase",
    "Forgot to go into the portal",
    "Wrong person or wrong portal",
    "Can't kill angelics",
    "Motes run out",
    "Troubles with jumping sections",
    "Death to Vex Instantiation",
    "Someone dies because of Voltaic Overflow",
    "Consecrated Mind Telefrag",
    '"Pulling" to an encounter',
    "Someone left out of the final tethers at second encounter",
    '"Pushing" shielded enemies',
    "Both portals open at once",
    "Someone dying to the pyramid",
    "Attempting a tether with a non-locked relay",
    "Dealing with the eyes from the middle",
    "Locked out during Consecrated DPS",
    "Depositing motes at the wrong relay",
    "Gambit team has no void weapons",
  ],
  "sotp": [
			"Anything other than CAP",
			"Comparison to a strike",
			"Dying in sparrow race",
			"No light in the maze",
			"Punching the corrupted symbol",
			"Getting lost in the maze",
			"Getting lost in the city",
			"Wrong beserker killed",
			"Beserker Shield isn't destroyed on the first pulse",
			"Shields are still up when the tank spawns",
			"Death due to tethering during DPS",
			"Vague map callouts",
			"Miscounted dots",
			"Tank spawn in the first encounter",
			"Failed ball duping",
			"Missed a button",
			"One person already at the next encounter while someone is still at the jumping part",
			"Confusion regarding where to deposit",
			"Snipers still up during DPS",
			"Boss not staggered",
			"Death to electricity",
			"Not using sparrows where they could be used",
			"Shanks underground",
			"Xeno DPS",
      "Radiance tethered",
			],
};

export default raids;
